<!ELEMENT	Cardinal		EMPTY>
<!ATTLIST	Cardinal  		unit  		CDATA 	#REQUIRED>

<!ELEMENT  	RealF			EMPTY>
<!ATTLIST	RealF			Cardinal	CDATA 	#REQUIRED
							realvalue	CDATA 	#REQUIRED>
<!ELEMENT  	RealD			EMPTY>
<!ATTLIST	RealD			Cardinal	CDATA 	#REQUIRED
							realvalue	CDATA 	#REQUIRED>
<!ELEMENT  	ComplexF		EMPTY>
<!ATTLIST	ComplexF		Cardinal	CDATA 	#REQUIRED
							realvalue	CDATA 	#REQUIRED
							imgvalue	CDATA 	#REQUIRED>
<!ELEMENT  	ComplexD		EMPTY>
<!ATTLIST	ComplexD		Cardinal	CDATA 	#REQUIRED
							realvalue	CDATA 	#REQUIRED
							imgvalue	CDATA 	#REQUIRED>
							
<!ELEMENT	Cardinals		(Cardinal+)>

<!ELEMENT	Foot			(Name)>

<!ELEMENT 	Weights 		((RealF|RealD|ComplexF|ComplexD)+)>
<!ATTLIST 	Weights			number 		CDATA 	#REQUIRED
							gradeKey	CDATA	#REQUIRED>

<!ELEMENT 	Monad 			(Weights)>
<!ATTLIST 	Monad 			name 		CDATA	#optional
							algebra		CDATA	#REQUIRED
							gradeKey	CDATA	#REQUIRED
							sparseFlag	CDATA	#REQUIRED>

<!ELEMENT 	MonadList 		(Monad+)>

<!ELEMENT	Nyad			(Foot,MonadList)>
<!ATTLIST 	Nyad 			name 		CDATA	#optional
							order 		CDATA	#REQUIRED
							algorder	CDATA	#REQUIRED>

<!ELEMENT 	NyadList 		(Nyad+)>
<!ATTLIST 	NyadList 		size		CDATA	#REQUIRED>